### PR TITLE
'Capitals bug' fixed for directories 'bad[01]{Code,Data}'

### PR DESCRIPTION
**Pull request by Wiimm**
The sub directories use uppercase letters, but the makefiles try to access them with lower case letters. This leads into "not found" errors on make using real file systems like ext*. I edited the make files to fix it.

### CODE REVIEW

**Comment by Chadderz121** [comment]
Hi @Wiimm,

Thanks for the patch, I'm surprised I didn't catch this myself, I'm fairly sure I did build it on Linux once, but evidently not.

I have no problems with cba779f571083abefd6793c8bba481b912a40a7f or a72aaf6a18fc270bd84597b36cb30695ab0489f1, but I'm a little less happy with the changes in 7deea3b798d6f28ae1739d4396a38c26b93f8738. Firstly, `mkdir -p` isn't necessarily portable, especially to Windows depending on the version of mingw/cygwin in use. Secondly, you make use of a phony target to create actual files in `szstools1`, which makes the makefile less able to do things like parallel make. This could be rewritten to 3 individual build rules easily. I also am not sure if the `{mod1,mod2,ovr1}.bin` syntax is portable, I can't find a reference for it on any POSIX shell specification. Finally, why is this `szstoolsdir` necessary at all? Can't you find the files in the build directory exactly as the szstools1 build rule does? The paths inside the build directory should be stable?

**Comment by Wiimm** [comment]
First, it was only planned to  pull-request the capitals fix. Then I made some changes that don't replace any code. My modification don't change anything of the old directory structure or any code. For real code modification I plan branches.

mkdir -p exists since System V (199x), FreeBSD (since beginning)  and is also available in Windows cmd. I have never worked with a system that don't support mkdir -p, and I'm old.

I'm not so sure about the "{mod1,mod2,ovr1}.bin" syntax, but I know and it for a long time. Maybe it is a bash extension.

szs-tools is needed, because it creates exact the files, that my SZS tools need; not less not more. And bad1code.bin was not created without the patch.

**Comment by Chadderz121** [comment]
Ah okay, I wonder how Github will react if I only accept the first commit. To clarify, you don't want the two other commits to be in this pull request?

I definitely have worked on a Windows machine recently where `mkdir -p` was not supported. It created a directory called `-p` as well as the target. It may well have been invoking a non-standard version of `mkdir`, but it's not to much trouble to make the full path manually in the makefile. e.g.
```makefile
build:
        mkdir build
build/bad1: build
        mkdir build/bad1
```
The only downside is the unnecessary detection of modifications to the directory, which remakes the target. Order only dependencies were introduced to fix this, but I have also worked on systems where these aren't supported either, so I prefer the less clear, but more portable:
```makefile
build:
        mkdir build
# build/bad1 depends on build if it doesn't exist.
build/bad1: $(filter-out $(wildcard build),build)
        mkdir build/bad1
```

Yes, I couldn't find any evidence that it wasn't a bashism, so I tend to assume it is :wink:

Ah, I see. My concern is that that creates a dependency between this repository and your tools, if ever you need a different set of files, I would have to accept a pull request here, and everyone would need to pull the changes. If you take the files directly from the build directory, no one will have to change anything.

**Comment by Wiimm** [comment]
Today I installed mingw (last release of 2013) and it supports mkdir -p. Cygwin supports its too. So I think there is no need to revert it.

So my offer is: I edit my changes to make it more compatible, try to satisfy your wishes and commit/push it again. And then you can merge it. I also plan to try and test the modifications of DimitriPilot3 in a new branch.

**Comment by Wiimm** [comment]
To verify your mkdir implementation I cloned the trunk again and tried:

# make bin/rmcp bin/rmce
bin
bin/rmcp
bin/rmce

fine up to here, but if repeating it, make throws a warning::
 # make bin/rmcp bin/rmce
bin/rmcp
mkdir: cannot create directory `bin/rmcp': File exists
make: [bin/rmcp] Error 1 (ignored)
make: `bin/rmce' is up to date.

Solution:
Either: mkdir -p $@
or: test -d $@ || mkdir $@

**Comment by Chadderz121** [comment]
Thanks for your patches and patience. I've fixed up a few little mistakes and merged into the main tree. Sorry it took so long!

**Pull request merged**
